version: '3.7'

services:
  web:
    image: shopapp
    container_name: testspring
    ports:
      - "8080:80"
    networks:
      - springboot-mysql-net
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shopapp
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456
#    networks:
#      - "springboot-mysql-net"
    networks:
    - springboot-mysql-net
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql