version: '3.7'

services:
  web:
    build: ./
    container_name: testspring
    ports:
      - "8080:8080"
    #cau hinh them khi chay jenkins tren docker
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shopapp
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - springboot-mysql-net
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shopapp
      MYSQL_USER: sa
      MYSQL_PASSWORD: 123456
#    networks:
#      - "springboot-mysql-net"
    networks:
    - springboot-mysql-net
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/root/.my.cnf
networks:
  springboot-mysql-net:
    name: springboot-mysql-net
    driver: bridge