spring :
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
#    url: jdbc:mysql://localhost:3306/shopapp
#    driver-class-name: com.mysql.jdbc.Driver
#    username: test
#    password: 123456
    url: jdbc:mysql://host.docker.internal:3306/shopapp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
#     url: jdbc:mysql://localhost:3306/shopapp
#     username: root
#     password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
          auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true

  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  profiles:
    active: docker

api:
  prefix: api/v1

jwt:
  expiration: 2592000 # 30days = 30*24*60*60
  secretKey: XPAknMdpzulJy4R7CtRyuZqcgisfv7YDsLvk3hIr52E=







