spring :
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
 #   url: jdbc:mysql://localhost:3306/shopapp
 #   driver-class-name: com.mysql.jdbc.Driver
 #   username: root
 #   password: admin
     url: jdbc:mysql://localhost:3306/shopapp
     username: root
     password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
          auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true

  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  profiles:
    active: docker

api:
  prefix: api/v1

jwt:
  expiration: 2592000 # 30days = 30*24*60*60
  secretKey: XPAknMdpzulJy4R7CtRyuZqcgisfv7YDsLvk3hIr52E=







